### ISSUE TITLE
Cmake doesn't find ffmpeg-2.6.2 on windows

### ISSUE THREAD

**Issue by xiaoweiChen** [scrawl/ogre-ffmpeg-videoplayer#1]
I find the last update of this repository is two month ago.

I clone this repo and download the ffmpeg 2.6.2, then set the environment variable for ffmpeg (FFMPEG_HOME), I work under windows 7 sp1.

However, when I do cmake in build directory, camke call me "can not found ffmpeg" Following words is in my screen.
```
-- Could NOT find FFmpeg (missing:  FFMPEG_LIBRARIES FFMPEG_INCLUDE_DIRS AVCODEC_LIBRARIES AVCODEC_INCLUDE_DIRS AVFORMAT
_LIBRARIES AVFORMAT_INCLUDE_DIRS AVUTIL_LIBRARIES AVUTIL_INCLUDE_DIRS SWSCALE_LIBRARIES SWSCALE_INCLUDE_DIRS)
CMake Error at CMakeLists.txt:26 (message):
  FFmpeg component required, but not found!
```

anyone can show me the supported ffmpeg version?
Or, there are have other solution for 2.6.2?

Thanks!!!

**Comment by scrawl** [comment]
I know that it works with ffmpeg 2.6.2. You seem to have hit an issue in your cmake setup. I can't help you with that though because I'm not using windows. I suggest debugging the cmake script to see the file paths its looking for.

**Comment by xiaoweiChen** [comment]
thanks scrawl,

I will try to debug CMakeLists.txt. 

And here, I want to make sure the FFMPEG_HOME is standand for ffmpeg resource code, or for ffmpeg Dev version form [here](http://ffmpeg.zeranoe.com/builds/) (fFFmpeg 64-bit Dev Versions)?

**Comment by xiaoweiChen** [comment]
FFmpeg Dev Versions is make cmakelists.txt worked.
