### ISSUE TITLE
Can not find the current libraries in Windows

### ISSUE THREAD

**Issue by xiaoweiChen** [scrawl/ogre-ffmpeg-videoplayer#2]
When I finish the cmake processing, I open the project by VS2013. 

The lib can build well. When building dome, the compiler give more `Unresolved external symbol` error.

The image about error
![1](https://cloud.githubusercontent.com/assets/2756670/7794120/92cc0586-02f9-11e5-80eb-0a79376c1ed8.PNG)

The configuration of ogre-ffmpeg-videoplayer-demo
![2](https://cloud.githubusercontent.com/assets/2756670/7794123/977d6232-02f9-11e5-8e0f-bdc6703b3fe2.PNG)

I change the order of the libs, but have no effect for the errors.

I know the author work under the Linux or Mac, if someone resolved this issue under windows 7, please tell me. 

Thanks!!

**Comment by scrawl** [comment]
Just a guess, I see you have boost_x86_vc120, but also ffmpeg-win64-dev. Are you mixing 32 bit libraries and 64 bit libraries? Is your project built as 32 or 64 bit? You have to pick one and stick to it.

**Comment by xiaoweiChen** [comment]
En... Yes, Friend, you are right, I mix 64bit and 32bit libraries.

Base on your suggestion, I download the latest version Boost and try to build the demo.

Configuration like below:
![1](https://cloud.githubusercontent.com/assets/2756670/7804204/fcbddd6e-0391-11e5-917e-48f07d551ef1.PNG)

And now, I meet the `error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'` error. 

And I use all 64bit libraries, so..... now, I don't know where is wrong.... @_@

@scrawl , some suggestions here?

**Comment by xiaoweiChen** [comment]
En... I change all libraries file to 32bit, everything work well.

Thanks **scrawl**!
